
spring.flyway.enabled: false

jndi.datasources.acl.enabled: false
pg.schema: ''
acl.db.dialect: org.hibernate.dialect.H2Dialect
acl.db.hbm2ddl.auto: create
acl.security.headers.enabled: true

geoserver.acl.datasource:
  url: jdbc:h2:mem:geoserver-acl;DB_CLOSE_DELAY=-1
  jndi-name: ''
  hikari:
    minimum-idle: 1
    maximum-pool-size: 20

